name = "CSC_Registry"
uuid = "4ce79c9b-a6c3-4293-a589-1456a01f7d8e"
repo = "https://github.com/FF-UH/CSC_Registry.jl"

[packages]
0c975e61-21d9-4454-8de5-ff08fd2c478f = { name = "SimpleLockFiles", path = "S/SimpleLockFiles" }
1070a898-5650-4dbc-bdc4-2f105286d314 = { name = "ObaASTs", path = "O/ObaASTs" }
1c3e8eab-fb9d-4faa-86a4-2d4d6165c1a6 = { name = "EasyEvents", path = "E/EasyEvents" }
1d417f3e-fd42-11ea-18da-dda57c9b97b2 = { name = "UtilsJL", path = "U/UtilsJL" }
2466591a-1acb-44b6-b4da-1e937b8575b3 = { name = "ObaServer", path = "O/ObaServer" }
25937451-55af-4cf1-a681-2354f35bf0f3 = { name = "PkgMassInstaller", path = "P/PkgMassInstaller" }
3cb95532-3c78-4535-bbc5-067405b402f6 = { name = "RegexTools", path = "R/RegexTools" }
466ec94f-58aa-4bf1-ae55-0fdfea5849a7 = { name = "PrintTools", path = "P/PrintTools" }
5c6ed6fa-ca7d-46d5-93ed-bd31318268f5 = { name = "RemAssistant", path = "R/RemAssistant" }
600230a9-b20f-4ec3-b56e-c0a439718caf = { name = "TexAssistant", path = "T/TexAssistant" }
60a16571-0043-4368-b1b0-a5366d36b020 = { name = "ImgTools", path = "I/ImgTools" }
638332cd-b357-4bf5-bfa2-3531168477f5 = { name = "FilesTreeTools", path = "F/FilesTreeTools" }
6bfc0cc1-c423-4851-8624-db00c2e00b7b = { name = "ExternalCmds", path = "E/ExternalCmds" }
769de9c1-ca9f-41ae-9e69-f7e27706da2c = { name = "BibUtils", path = "B/BibUtils" }
772e7830-88e0-466f-82c6-af9b8962b67b = { name = "GWUtils", path = "G/GWUtils" }
82dba31a-8ab6-430f-a22d-9cbb81344561 = { name = "DataFileNames", path = "D/DataFileNames" }
94559648-8665-43eb-95be-b874d653e167 = { name = "MetEP", path = "M/MetEP" }
948146ab-812c-48a7-a07f-51ea6ea1546c = { name = "MagicDicts", path = "M/MagicDicts" }
9e5d5e8c-ba81-11ea-39e8-15323c797f61 = { name = "GitWorkers", path = "G/GitWorkers" }
a87e7f4e-3b34-4b5e-ad6b-f0ab85127471 = { name = "ChemostatPlots", path = "C/ChemostatPlots" }
b110ed5b-1827-4ea4-a31c-50efd441af06 = { name = "JLAssistant", path = "J/JLAssistant" }
bb7579a6-17cc-4454-bc80-c1b83f10c6c8 = { name = "MetLP", path = "M/MetLP" }
bfe2832f-5600-46d7-a449-140889a58637 = { name = "StringRepFilter", path = "S/StringRepFilter" }
c1c1e88c-cb6c-463d-9723-3dce2b3356d0 = { name = "MyPkgTemplate", path = "M/MyPkgTemplate" }
c5987326-81b3-11ea-28dd-b531745de20f = { name = "Chemostat", path = "C/Chemostat" }
d690c95a-5dbf-4f48-8541-cd6f672b0d00 = { name = "SimTools", path = "S/SimTools" }
df388e3e-013c-4f8d-ba67-f4afa1ff006b = { name = "ProjAssistant", path = "P/ProjAssistant" }
e5655290-0136-40fd-b997-9e22755203bc = { name = "GitLinks", path = "G/GitLinks" }
e57bcde5-101c-47b4-bac9-e79e238e37d4 = { name = "MetNets", path = "M/MetNets" }
e83e49e0-9c73-11ea-0f72-7b2612c12766 = { name = "Example", path = "E/Example" }
ef2754c0-c555-4d81-bf39-f3e359f0c7f3 = { name = "ObsidianAssistant", path = "O/ObsidianAssistant" }
fbbb76bd-cc92-4b2f-9b7e-8d53a46f5940 = { name = "INOAssistant", path = "I/INOAssistant" }
